name: install-build-test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [10.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test:ci

      - name: Run linters
        run: yarn lint

        env:
          CI: true
